
// All data are fictional; ranking uses exchange cards only, never profile attributes.
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let mine=[{id:'m1',give:'PPT 排版',want:'英语口语',goal:'修改并练习英文自我介绍',time:'周三晚上',flex:true,minutes:30,mode:'线上实时',pay:false,charge:false},{id:'m2',give:'Excel 公式',want:'手机摄影',goal:'学会拍摄一张美食照片',time:'周六上午',flex:true,minutes:30,mode:'线上实时',pay:false,charge:false}],active='m1',focus='learn',filter='all',index=0,shown=[],saved=new Set(),skipped=new Set(),invited=new Set();
const candidates=[{id:'c1',owner:'zhou',name:'小周',give:'英语口语',want:'PPT 排版',goal:'优化一页求职作品集',desc:'修改自我介绍初稿，练习表达和发音。',time:'周三晚上',flex:false,minutes:30,mode:'线上实时',pay:false,charge:false},{id:'c2',owner:'chen',name:'小陈',give:'英语口语',want:'PPT 排版',goal:'调整汇报页的信息层级',desc:'梳理表达结构，练习一段 60 秒自我介绍。',time:'周日晚上',flex:true,minutes:30,mode:'线上实时',pay:true,charge:false},{id:'c3',owner:'lin',name:'小林',give:'手机摄影',want:'Excel 公式',goal:'用 SUMIF 完成条件求和',desc:'练习光线与构图，拍摄一张美食照片。',time:'周六上午',flex:true,minutes:30,mode:'线上实时',pay:false,charge:false},{id:'c4',owner:'yu',name:'小雨',give:'手机摄影',want:'Excel 公式',goal:'学会基础查找公式',desc:'用日常物品练习静物拍摄。',time:'周日晚上',flex:true,minutes:30,mode:'线上实时',pay:false,charge:false}];
let invitations=[];
const profiles={zhou:'有英文汇报经验，喜欢把复杂内容讲清楚。',chen:'喜欢口语练习和知识分享。',lin:'手机摄影爱好者，正在学习表格处理。',yu:'喜欢生活摄影，想提高日常办公效率。'};
try { const data=JSON.parse(localStorage.getItem('dabashou-cards-v2')||'null'); if(data && Array.isArray(data.mine) && data.mine.length<=3 && data.mine.every(c=>c && typeof c.id==='string' && typeof c.give==='string' && typeof c.want==='string')) { mine=data.mine;active=mine.some(c=>c.id===data.active)?data.active:mine[0]?.id;saved=new Set(data.saved||[]);skipped=new Set(data.skipped||[]);invited=new Set(data.invited||[]);invitations=Array.isArray(data.invitations)?data.invitations:[]; } } catch {}
function persist(){try{localStorage.setItem('dabashou-cards-v2',JSON.stringify({mine,active,saved:[...saved],skipped:[...skipped],invited:[...invited],invitations}))}catch{toast('暂时无法保存，刷新后可能恢复示例数据')}}
const key=c=>active+':'+c.id,current=()=>mine.find(c=>c.id===active);
function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),2500)}
function open(t,html){$('#modal-title').textContent=t;$('#body').innerHTML=html;if(!$('#modal').open)$('#modal').showModal()}
$('#close').onclick=()=>$('#modal').close();
function matches(){let a=current();if(!a||a.charge)return[];let list=candidates.filter(b=>!b.charge&&a.want===b.give&&a.give===b.want&&a.mode===b.mode&&(a.time===b.time||a.flex||b.flex)&&!skipped.has(key(b)));list=list.filter(b=>filter==='all'||(filter==='time'?a.time===b.time:a.time!==b.time));list.sort((b,c)=>Number(c.time===a.time)-Number(b.time===a.time));let seen=new Set();return list.filter(b=>seen.has(b.owner)?false:(seen.add(b.owner),true))}
function render(){ persist(); $('#quota').textContent=mine.length+'/3';$('#savedcount').textContent=saved.size;$('#mylist').innerHTML=mine.map(c=>`<button class="mine ${c.id===active?'selected':''}" data-select="${c.id}" aria-pressed="${c.id===active}"><small>想学技能</small><strong>${esc(c.want)}</strong><small>我的技能 · ${esc(c.give)}</small></button>`).join('')||'<small>先创建一张交换卡</small>';document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{active=b.dataset.select;render()});shown=matches();index=0;$('#deck').innerHTML=shown.map(cardHTML).join('')||`<div class="empty"><h2>${current()?.charge?'费用意向已保存':'暂无互补的交换卡'}</h2><p>${current()?.charge?'首版暂不开放付费教学。':'可以调整技能或可用时间。'}</p><button id="empty-edit">${mine.length?'编辑我的卡片':'创建交换卡'}</button><button class="quiet" id="restore">重置筛选与跳过</button></div>`;$('#deck').scrollTop=0;bindCards();if($('#empty-edit'))$('#empty-edit').onclick=()=>edit(current()?.id);if($('#restore'))$('#restore').onclick=()=>{filter='all';skipped=new Set([...skipped].filter(k=>!k.startsWith(active+':')));document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.filter==='all'));render()};updateNav()}
function cardHTML(c){let same=c.time===current().time;let give=`<section class="skill ${focus==='learn'?'learn':''}"><label>我的技能</label><h2>${esc(c.give)}</h2><p>${esc(c.desc)}</p></section>`,want=`<section class="skill ${focus==='teach'?'learn':''}"><label>想学技能</label><h2>${esc(c.want)}</h2><p>${esc(c.goal)}</p></section>`;return `<article class="card" data-card="${c.id}"><div class="flex"><div class="who"><span class="avatar" aria-hidden="true">${c.name.slice(-1)}</span><strong>${c.name}的交换卡</strong></div><span class="pill ${same?'':'warn'}">${same?'有共同时间':'时间可协商'}</span></div><div class="exchange">${focus==='learn'?give+want:want+give}</div><div class="conditions"><div class="condition"><span>时间</span><span>${esc(c.time)}${c.flex?' · 可协商':''}</span></div><div class="condition"><span>投入</span><span>双方各 ${c.minutes} 分钟 · 单次</span></div><div class="condition"><span>方式</span><span>${c.mode}</span></div></div><div class="fees"><span>愿意支付费用：${c.pay?'是':'否'}</span><span>要求支付费用：${c.charge?'是':'否'}</span></div><div class="reason">${same?'技能双向互补 · 时间一致':'技能双向互补 · 时间待确认'}</div><div class="cardbottom"><div class="utility"><button class="quiet" data-profile="${c.id}">查看用户档案</button><button class="quiet" data-skip="${c.id}">暂不考虑</button></div><div class="actions"><button data-save="${c.id}" aria-pressed="${saved.has(key(c))}">${saved.has(key(c))?'已收藏':'收藏'}</button><button class="primary" data-invite="${c.id}" ${invited.has(key(c))?'disabled':''}>${invited.has(key(c))?'待对方回应':'发起互换'}</button></div></div></article>`}
function updateNav(){let empty=!shown.length;$('#position').textContent=empty?'':`${index+1} / ${shown.length} · 上下滑动`;$('#prev').disabled=empty||index===0;$('#next').disabled=empty||index===shown.length-1}
function go(i){let cards=[...document.querySelectorAll('.card')];if(cards[i])$('#deck').scrollTo({top:cards[i].offsetTop-cards[0].offsetTop,behavior:'auto'})}
$('#prev').onclick=()=>go(index-1);$('#next').onclick=()=>go(index+1);$('#deck').onscroll=()=>{let cards=[...document.querySelectorAll('.card')];if(!cards.length)return;index=cards.reduce((best,c,i)=>Math.abs(c.offsetTop-cards[0].offsetTop-$('#deck').scrollTop)<Math.abs(cards[best].offsetTop-cards[0].offsetTop-$('#deck').scrollTop)?i:best,0);updateNav()};$('#deck').onkeydown=e=>{if(e.target!==$('#deck'))return;if(e.key==='ArrowDown'){e.preventDefault();go(index+1)}if(e.key==='ArrowUp'){e.preventDefault();go(index-1)}};
document.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>{focus=b.dataset.focus;document.querySelectorAll('[data-focus]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()});
function bindCards(){document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{let c=candidates.find(c=>c.id===b.dataset.profile);open(c.name,`<div class="fields"><p>${profiles[c.owner]}</p><small>自述信息 · 未经认证</small><p>当前技能：${esc(c.give)}</p><p>想学技能：${esc(c.want)}</p></div>`)});document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{let c=candidates.find(c=>c.id===b.dataset.save),k=key(c);saved.has(k)?saved.delete(k):saved.add(k);b.textContent=saved.has(k)?'已收藏':'收藏';b.setAttribute('aria-pressed',saved.has(k));$('#savedcount').textContent=saved.size;persist();toast(saved.has(k)?'已收藏，仅自己可见':'已取消收藏')});document.querySelectorAll('[data-skip]').forEach(b=>b.onclick=()=>{open('暂不考虑',`<div class="fields"><label>原因（选填）<select id="skipreason"><option>暂时跳过</option><option>时间不合适</option><option>内容不适合</option></select></label></div><div class="dialogactions"><button id="skipconfirm">跳过这张卡</button></div>`);$('#skipconfirm').onclick=()=>{skipped.add(active+':'+b.dataset.skip);$('#modal').close();render();toast('已跳过当前方案')}});document.querySelectorAll('[data-invite]').forEach(b=>b.onclick=()=>invite(b.dataset.invite))}
function invite(id){let c=candidates.find(x=>x.id===id),a=current(),k=key(c);open('确认互换',`<div class="fields"><p>我学 ${esc(c.give)}，我教 ${esc(a.give)}</p><small>双方各 30 分钟 · 线上实时 · 模拟邀请</small><label>提议时间<input id="when" type="datetime-local" required></label><label class="check"><input id="negotiate" type="checkbox">可协商</label></div><div class="dialogactions"><button class="primary" id="send">发送邀请</button></div>`);$('#send').onclick=()=>{if(!$('#when').value&&!$('#negotiate').checked){$('#when').reportValidity();return}if($('#when').value && new Date($('#when').value)<=new Date()){toast('请选择未来的日期和时间');return}invitations.unshift({id:Date.now(),key:k,name:c.name,give:a.give,want:c.give,goal:a.goal,theirGoal:c.goal,when:$('#when').value,flex:$('#negotiate').checked});invited.add(k);$('#modal').close();render();toast('模拟邀请已发出，待对方回应')}}
function manage(){open('我的交换卡',`<div class="fields">${mine.map(c=>`<div class="editrow"><button class="mine" data-edit="${c.id}"><strong>${esc(c.give)} ⇄ ${esc(c.want)}</strong><small>${esc(c.time)}${c.flex?' · 可协商':''}</small></button><button class="quiet" data-delete="${c.id}">删除</button></div>`).join('')}</div><div class="flex"><small>最多 3 张 · 当前 ${mine.length} 张</small><button id="add" class="primary" ${mine.length>=3?'disabled':''}>新建交换卡</button></div>`);$('#add').onclick=()=>edit();document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{let removed=b.dataset.delete;mine=mine.filter(c=>c.id!==removed);saved=new Set([...saved].filter(k=>!k.startsWith(removed+':')));skipped=new Set([...skipped].filter(k=>!k.startsWith(removed+':')));if(!current())active=mine[0]?.id;render();manage()})}
$('#manage').onclick=manage;
const skills=['PPT 排版','Excel 公式','英语口语','手机摄影','短视频剪辑'];function options(items,value){return items.map(s=>`<option ${s===value?'selected':''}>${esc(s)}</option>`).join('')}
function edit(id){let c=mine.find(x=>x.id===id)||{give:'PPT 排版',want:'英语口语',goal:'',time:'周三晚上',flex:true,pay:false,charge:false};open(id?'编辑交换卡':'新建交换卡',`<form id="editor"><div class="fields"><label>我的技能<select name="give">${options(skills,c.give)}</select></label><label>想学技能<select name="want">${options(skills,c.want)}</select></label><label>学习目标<textarea name="goal" maxlength="80" required placeholder="想完成什么具体任务">${esc(c.goal)}</textarea></label><label>时间<select name="time">${options(['周三晚上','周六上午','周日晚上'],c.time)}</select></label><label class="check"><input name="flex" type="checkbox" ${c.flex?'checked':''}>可协商</label><small>线上实时 · 双方各 30 分钟</small><label class="check"><input name="pay" type="checkbox" ${c.pay?'checked':''}>愿意支付费用</label><label class="check"><input name="charge" type="checkbox" ${c.charge?'checked':''}>要求支付费用</label><small>费用仅作备注，首版暂不开放付费教学。</small><p id="fee-warning" class="notice ${c.charge?'':'hidden'}">要求支付费用的卡片暂不参与互换推荐。</p></div><div class="dialogactions"><button class="primary" type="submit">保存</button></div></form>`);let form=$('#editor');form.elements.charge.onchange=()=>$('#fee-warning').classList.toggle('hidden',!form.elements.charge.checked);form.onsubmit=e=>{e.preventDefault();if(!id&&mine.length>=3){toast('最多创建 3 张交换卡');return}let data=new FormData(form),n={id:id||'m'+Date.now(),give:data.get('give'),want:data.get('want'),goal:data.get('goal').trim(),time:data.get('time'),flex:data.has('flex'),pay:data.has('pay'),charge:data.has('charge'),minutes:30,mode:'线上实时'};if(n.give===n.want){toast('请选择两项不同的技能进行互换');return}if(!n.goal){form.elements.goal.setCustomValidity('请填写学习目标');form.elements.goal.reportValidity();return}if(id)mine=mine.map(x=>x.id===id?n:x);else mine.push(n);active=n.id;$('#modal').close();render()};form.elements.goal.oninput=()=>form.elements.goal.setCustomValidity('')}
$('#collections').onclick=()=>{let list=[...saved].map(k=>({k,m:mine.find(m=>m.id===k.split(':')[0]),c:candidates.find(c=>c.id===k.split(':')[1])})).filter(x=>x.m&&x.c);open('收藏',list.length?list.map(x=>`<div class="savedrow"><strong>${x.c.name} · ${x.c.give}</strong><p>${x.m.give} ⇄ ${x.c.give}</p><button data-return="${x.k}">回看卡片</button></div>`).join(''):'<p class="muted">暂无收藏</p>');document.querySelectorAll('[data-return]').forEach(b=>b.onclick=()=>{let [m,c]=b.dataset.return.split(':');active=m;filter='all';skipped.delete(b.dataset.return);document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.filter==='all'));$('#modal').close();render();go(shown.findIndex(x=>x.id===c))})};render();

function page(name){
 document.querySelectorAll('[data-page]').forEach(b=>{if(b.dataset.page===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});
 $('#discovery').hidden=name!=='discover';$('#secondary').hidden=name==='discover';
 if(name==='discover'){render();return}
 if(name==='mine'){
 $('#secondary').innerHTML=`<div class="page-heading"><h1>我的交换卡</h1><p class="muted">一张卡，一组具体供需。最多创建三张。</p></div><div class="myoverview">${mine.map(c=>`<article class="overview"><small>我的技能 → 想学技能</small><h2>${esc(c.give)} ⇄ ${esc(c.want)}</h2><p>${esc(c.goal)}</p><small>${esc(c.time)}${c.flex?' · 可协商':''} · 双方各 30 分钟</small></article>`).join('')||'<p>还没有交换卡，创建一张开始匹配。</p>'}</div><button class="primary" id="manage-page">管理交换卡</button><p class="cap">资料仅保存在此浏览器，暂不提供账号与云端同步。</p>`;
 $('#manage-page').onclick=manage;
 }else{
 $('#secondary').innerHTML=`<div class="page-heading"><h1>我的互换</h1><p class="muted">查看已发出的邀请，等待对方回应。</p></div>${invitations.length?invitations.map(e=>`<article class="invitation"><div class="flex"><h2>与${esc(e.name)}的互换</h2><span class="pill">待对方回应</span></div><p>我教 ${esc(e.give)} · 我学 ${esc(e.want)}</p><p class="muted">我的目标：${esc(e.goal)}</p><p class="muted">对方目标：${esc(e.theirGoal)}</p><p class="muted">${e.when?esc(e.when.replace('T',' ')):'尚未确定时间'}${e.flex?' · 可协商':''} · 双方各 30 分钟 · 线上实时</p><small>模拟邀请。对方尚未确认，不代表已经预约。</small><button class="quiet" data-withdraw="${e.id}">撤回邀请</button></article>`).join(''):'<div class="empty"><h2>还没有互换邀请</h2><p>从一张互补的交换卡开始。</p><button class="primary" id="find-partner">去发现</button></div>'}`;
 if($('#find-partner'))$('#find-partner').onclick=()=>page('discover');
 document.querySelectorAll('[data-withdraw]').forEach(b=>b.onclick=()=>{let e=invitations.find(x=>x.id===Number(b.dataset.withdraw));invited.delete(e.key);invitations=invitations.filter(x=>x.id!==e.id);persist();page('exchanges');toast('已撤回模拟邀请')});
 }
}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));$('.brand').onclick=e=>{e.preventDefault();page('discover')};
$('#modal').addEventListener('close',()=>{const activePage=document.querySelector('[data-page][aria-current]')?.dataset.page;if(activePage==='mine')page('mine')});
